import type { AcademyParams } from "@/lib/academy/simulate"
import { useState } from "react"
import { parseUnits } from "viem"

type Props = {
  params: AcademyParams
  onChange: (next: AcademyParams) => void
  onReset: () => void
}

const SEMESTER_PRESETS: ReadonlyArray<{ label: string; mezo: number }> = [
  { label: "S0 · 1M", mezo: 1_000_000 },
  { label: "S1 · 4M", mezo: 4_000_000 },
  { label: "S2 · 10M", mezo: 10_000_000 },
  { label: "S3 · 4M", mezo: 4_000_000 },
]

function mezoToWad(mezo: number): bigint {
  if (!Number.isFinite(mezo) || mezo <= 0) return 0n
  return parseUnits(mezo.toFixed(6), 18)
}

function wadToMezo(wad: bigint): number {
  if (wad <= 0n) return 0
  return Number(wad / 10n ** 12n) / 1e6
}

function Section({
  title,
  hint,
  children,
}: {
  title: string
  hint?: string
  children: React.ReactNode
}) {
  return (
    <div className="rounded border border-[var(--border)] bg-[var(--surface)] p-3">
      <div className="mb-2">
        <h4 className="text-xs font-semibold uppercase tracking-wider text-[var(--content-primary)]">
          {title}
        </h4>
        {hint ? (
          <p className="mt-0.5 text-[11px] leading-snug text-[var(--content-secondary)]">
            {hint}
          </p>
        ) : null}
      </div>
      {children}
    </div>
  )
}

function NumberField({
  label,
  value,
  step,
  min,
  max,
  onChange,
  hint,
}: {
  label: string
  value: number
  step: number
  min?: number
  max?: number
  onChange: (n: number) => void
  hint?: string
}) {
  return (
    <label className="flex flex-col gap-1">
      <span className="text-[11px] uppercase tracking-wider text-[var(--content-secondary)]">
        {label}
      </span>
      <input
        type="number"
        value={value}
        step={step}
        {...(min !== undefined ? { min } : {})}
        {...(max !== undefined ? { max } : {})}
        onChange={(e) => {
          const next = Number(e.target.value)
          onChange(Number.isFinite(next) ? next : 0)
        }}
        className="rounded border border-[var(--border)] bg-[var(--surface-tertiary)] px-2 py-1 text-sm text-[var(--content-primary)] outline-none focus:border-[#F7931A]"
      />
      {hint ? (
        <span className="text-[11px] leading-snug text-[var(--content-tertiary)]">
          {hint}
        </span>
      ) : null}
    </label>
  )
}

export default function AcademyKnobs({ params, onChange, onReset }: Props) {
  const currentBudgetMezo = Math.round(wadToMezo(params.budgetMezoWad))
  const [lastClickedPresetLabel, setLastClickedPresetLabel] = useState<
    string | null
  >(null)

  const activePreset = SEMESTER_PRESETS.find(
    (p) => p.label === lastClickedPresetLabel,
  )
  const isClickedPresetStillValid =
    activePreset && activePreset.mezo === currentBudgetMezo

  const activeLabel = isClickedPresetStillValid
    ? lastClickedPresetLabel
    : (SEMESTER_PRESETS.find((p) => p.mezo === currentBudgetMezo)?.label ??
      null)

  const update = (patch: Partial<AcademyParams>) => {
    if (patch.budgetMezoWad !== undefined) {
      const nextMezo = Math.round(wadToMezo(patch.budgetMezoWad))
      if (activePreset && activePreset.mezo !== nextMezo) {
        setLastClickedPresetLabel(null)
      }
    }
    onChange({ ...params, ...patch })
  }

  return (
    <div className="flex flex-col gap-3">
      <Section
        title="Reward Budget"
        hint="Total MEZO distributed across all participants this period. Allocation is proportional to each actor's points share."
      >
        <div className="flex flex-wrap gap-1.5">
          {SEMESTER_PRESETS.map((preset) => {
            const isActive = activeLabel === preset.label
            return (
              <button
                type="button"
                key={preset.label}
                onClick={() => {
                  setLastClickedPresetLabel(preset.label)
                  update({ budgetMezoWad: mezoToWad(preset.mezo) })
                }}
                className={`rounded px-2 py-1 text-xs font-semibold uppercase tracking-wider transition-colors ${
                  isActive
                    ? "bg-[#F7931A]/15 text-[#F7931A] ring-1 ring-inset ring-[#F7931A]/30"
                    : "bg-[var(--surface-tertiary)] text-[var(--content-primary)] hover:bg-[var(--surface-secondary)]"
                }`}
              >
                {preset.label}
              </button>
            )
          })}
        </div>
        <div className="mt-2">
          <NumberField
            label="Budget (MEZO)"
            value={currentBudgetMezo}
            step={100_000}
            min={0}
            onChange={(n) => update({ budgetMezoWad: mezoToWad(n) })}
          />
        </div>
      </Section>

      <Section
        title="Action Weights"
        hint="Points awarded per veMEZO of ve-power generated by each action. Higher weight = more rewards for that behavior."
      >
        <div className="grid grid-cols-3 gap-2">
          <NumberField
            label="New lock"
            value={params.weightNew}
            step={0.5}
            min={0}
            onChange={(n) => update({ weightNew: n })}
            hint="× ve-power of the new lock"
          />
          <NumberField
            label="Extension"
            value={params.weightExt}
            step={0.5}
            min={0}
            onChange={(n) => update({ weightExt: n })}
            hint="× delta ve-power vs prior lock state"
          />
          <NumberField
            label="Boost vote"
            value={params.weightBoost}
            step={0.5}
            min={0}
            onChange={(n) => update({ weightBoost: n })}
            hint="× weight cast on each vote"
          />
        </div>
      </Section>

      <Section
        title="Participation Bonus"
        hint="Reward consistent voters who stay active across the full selected range."
      >
        <div className="grid grid-cols-1 gap-2">
          <NumberField
            label="Full-epoch ×"
            value={params.participationMultiplier}
            step={0.25}
            min={1}
            max={5}
            onChange={(n) => update({ participationMultiplier: n })}
            hint="Multiplier on total earned points if actor voted in every epoch of the range"
          />
        </div>
      </Section>

      <Section
        title="Reward Floor"
        hint="Actors whose initial pro-rata reward falls below this MEZO amount are culled (reward → 0) and the forfeited share is redistributed to the remaining actors in proportion to points. Set to 0 to disable."
      >
        <NumberField
          label="Floor (MEZO)"
          value={Math.round(wadToMezo(params.rewardFloorMezoWad))}
          step={1}
          min={0}
          onChange={(n) => update({ rewardFloorMezoWad: mezoToWad(n) })}
          hint="Default 20 — keeps the pool from being smeared too thin."
        />
      </Section>

      <Section
        title="APR Conversion"
        hint="Only used to render the APR column on the leaderboard. Does not affect rewards."
      >
        <NumberField
          label="MEZO price (USD)"
          value={params.mezoUsd}
          step={0.01}
          min={0}
          onChange={(n) => update({ mezoUsd: n })}
        />
      </Section>

      <button
        type="button"
        onClick={() => {
          setLastClickedPresetLabel(null)
          onReset()
        }}
        className="self-start rounded border border-[var(--border)] bg-[var(--surface-tertiary)] px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-[var(--content-secondary)] hover:bg-[var(--surface-secondary)] hover:text-[var(--content-primary)]"
      >
        Reset to defaults
      </button>
    </div>
  )
}
