/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as QueryRouteImport } from './routes/query'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as GaugesAddressRouteImport } from './routes/gauges.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const GaugesAddressRoute = GaugesAddressRouteImport.update({
  id: '/gauges/$address',
  path: '/gauges/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/query': typeof QueryRoute
  '/rewards': typeof RewardsRoute
  '/vote': typeof VoteRoute
  '/gauges/$address': typeof GaugesAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/query': typeof QueryRoute
  '/rewards': typeof RewardsRoute
  '/vote': typeof VoteRoute
  '/gauges/$address': typeof GaugesAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/query': typeof QueryRoute
  '/rewards': typeof RewardsRoute
  '/vote': typeof VoteRoute
  '/gauges/$address': typeof GaugesAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/query'
    | '/rewards'
    | '/vote'
    | '/gauges/$address'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity' | '/query' | '/rewards' | '/vote' | '/gauges/$address'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/query'
    | '/rewards'
    | '/vote'
    | '/gauges/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  QueryRoute: typeof QueryRoute
  RewardsRoute: typeof RewardsRoute
  VoteRoute: typeof VoteRoute
  GaugesAddressRoute: typeof GaugesAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauges/$address': {
      id: '/gauges/$address'
      path: '/gauges/$address'
      fullPath: '/gauges/$address'
      preLoaderRoute: typeof GaugesAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  QueryRoute: QueryRoute,
  RewardsRoute: RewardsRoute,
  VoteRoute: VoteRoute,
  GaugesAddressRoute: GaugesAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
