/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ShowcaseRouteImport } from './routes/[_]showcase'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AuthRecoverRouteImport } from './routes/_auth/recover'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAppsRouteImport } from './routes/_app/admin/apps'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminQuotasRouteImport } from './routes/_app/admin/quotas'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppAppsAppIdRouteImport } from './routes/_app/apps/$appId'
import { Route as AppDocsIndexRouteImport } from './routes/_app/docs/index'
import { Route as AppDocsPageRouteImport } from './routes/_app/docs/$page'
import { Route as AppDocsReferenceRouteImport } from './routes/_app/docs/reference'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth/invite.$token'
import { Route as AppAdminReviewsReviewIdRouteImport } from './routes/_app/admin/reviews.$reviewId'
import { Route as AppAppsAppIdIndexRouteImport } from './routes/_app/apps/$appId/index'
import { Route as AppAppsAppIdEnvironmentsRouteImport } from './routes/_app/apps/$appId/environments'
import { Route as AppAppsAppIdKeysRouteImport } from './routes/_app/apps/$appId/keys'
import { Route as AppAppsAppIdOauthRouteImport } from './routes/_app/apps/$appId/oauth'
import { Route as AppAppsAppIdSecretsRouteImport } from './routes/_app/apps/$appId/secrets'
import { Route as AppAppsAppIdSettingsRouteImport } from './routes/_app/apps/$appId/settings'
import { Route as AppAppsAppIdUsageRouteImport } from './routes/_app/apps/$appId/usage'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/_showcase',
  path: '/_showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAppsRoute = AppAdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminQuotasRoute = AppAdminQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsIndexRoute = AppDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocsRoute,
} as any)
const AppDocsPageRoute = AppDocsPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppDocsRoute,
} as any)
const AppDocsReferenceRoute = AppDocsReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => AppDocsRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppAdminReviewsReviewIdRoute = AppAdminReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAppsAppIdIndexRoute = AppAppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdEnvironmentsRoute =
  AppAppsAppIdEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => AppAppsAppIdRoute,
  } as any)
const AppAppsAppIdKeysRoute = AppAppsAppIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdOauthRoute = AppAppsAppIdOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdSecretsRoute = AppAppsAppIdSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdSettingsRoute = AppAppsAppIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdUsageRoute = AppAppsAppIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/_showcase': typeof ShowcaseRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/docs': typeof AppDocsRouteWithChildren
  '/organization': typeof AppOrganizationRoute
  '/usage': typeof AppUsageRoute
  '/recover': typeof AuthRecoverRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin/apps': typeof AppAdminAppsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/quotas': typeof AppAdminQuotasRoute
  '/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/docs/$page': typeof AppDocsPageRoute
  '/docs/reference': typeof AppDocsReferenceRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/admin/': typeof AppAdminIndexRoute
  '/apps/': typeof AppAppsIndexRoute
  '/docs/': typeof AppDocsIndexRoute
  '/admin/reviews/$reviewId': typeof AppAdminReviewsReviewIdRoute
  '/apps/$appId/environments': typeof AppAppsAppIdEnvironmentsRoute
  '/apps/$appId/keys': typeof AppAppsAppIdKeysRoute
  '/apps/$appId/oauth': typeof AppAppsAppIdOauthRoute
  '/apps/$appId/secrets': typeof AppAppsAppIdSecretsRoute
  '/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/apps/$appId/usage': typeof AppAppsAppIdUsageRoute
  '/apps/$appId/': typeof AppAppsAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/_showcase': typeof ShowcaseRoute
  '/account': typeof AppAccountRoute
  '/organization': typeof AppOrganizationRoute
  '/usage': typeof AppUsageRoute
  '/recover': typeof AuthRecoverRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin/apps': typeof AppAdminAppsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/quotas': typeof AppAdminQuotasRoute
  '/docs/$page': typeof AppDocsPageRoute
  '/docs/reference': typeof AppDocsReferenceRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/admin': typeof AppAdminIndexRoute
  '/apps': typeof AppAppsIndexRoute
  '/docs': typeof AppDocsIndexRoute
  '/admin/reviews/$reviewId': typeof AppAdminReviewsReviewIdRoute
  '/apps/$appId/environments': typeof AppAppsAppIdEnvironmentsRoute
  '/apps/$appId/keys': typeof AppAppsAppIdKeysRoute
  '/apps/$appId/oauth': typeof AppAppsAppIdOauthRoute
  '/apps/$appId/secrets': typeof AppAppsAppIdSecretsRoute
  '/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/apps/$appId/usage': typeof AppAppsAppIdUsageRoute
  '/apps/$appId': typeof AppAppsAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_showcase': typeof ShowcaseRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/docs': typeof AppDocsRouteWithChildren
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/usage': typeof AppUsageRoute
  '/_auth/recover': typeof AuthRecoverRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/apps': typeof AppAdminAppsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/quotas': typeof AppAdminQuotasRoute
  '/_app/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/_app/docs/$page': typeof AppDocsPageRoute
  '/_app/docs/reference': typeof AppDocsReferenceRoute
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/docs/': typeof AppDocsIndexRoute
  '/_app/admin/reviews/$reviewId': typeof AppAdminReviewsReviewIdRoute
  '/_app/apps/$appId/environments': typeof AppAppsAppIdEnvironmentsRoute
  '/_app/apps/$appId/keys': typeof AppAppsAppIdKeysRoute
  '/_app/apps/$appId/oauth': typeof AppAppsAppIdOauthRoute
  '/_app/apps/$appId/secrets': typeof AppAppsAppIdSecretsRoute
  '/_app/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/_app/apps/$appId/usage': typeof AppAppsAppIdUsageRoute
  '/_app/apps/$appId/': typeof AppAppsAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_showcase'
    | '/account'
    | '/admin'
    | '/docs'
    | '/organization'
    | '/usage'
    | '/recover'
    | '/sign-in'
    | '/sign-up'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/quotas'
    | '/apps/$appId'
    | '/docs/$page'
    | '/docs/reference'
    | '/invite/$token'
    | '/admin/'
    | '/apps/'
    | '/docs/'
    | '/admin/reviews/$reviewId'
    | '/apps/$appId/environments'
    | '/apps/$appId/keys'
    | '/apps/$appId/oauth'
    | '/apps/$appId/secrets'
    | '/apps/$appId/settings'
    | '/apps/$appId/usage'
    | '/apps/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_showcase'
    | '/account'
    | '/organization'
    | '/usage'
    | '/recover'
    | '/sign-in'
    | '/sign-up'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/quotas'
    | '/docs/$page'
    | '/docs/reference'
    | '/invite/$token'
    | '/admin'
    | '/apps'
    | '/docs'
    | '/admin/reviews/$reviewId'
    | '/apps/$appId/environments'
    | '/apps/$appId/keys'
    | '/apps/$appId/oauth'
    | '/apps/$appId/secrets'
    | '/apps/$appId/settings'
    | '/apps/$appId/usage'
    | '/apps/$appId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_showcase'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/docs'
    | '/_app/organization'
    | '/_app/usage'
    | '/_auth/recover'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/admin/apps'
    | '/_app/admin/audit'
    | '/_app/admin/quotas'
    | '/_app/apps/$appId'
    | '/_app/docs/$page'
    | '/_app/docs/reference'
    | '/_auth/invite/$token'
    | '/_app/admin/'
    | '/_app/apps/'
    | '/_app/docs/'
    | '/_app/admin/reviews/$reviewId'
    | '/_app/apps/$appId/environments'
    | '/_app/apps/$appId/keys'
    | '/_app/apps/$appId/oauth'
    | '/_app/apps/$appId/secrets'
    | '/_app/apps/$appId/settings'
    | '/_app/apps/$appId/usage'
    | '/_app/apps/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_showcase': {
      id: '/_showcase'
      path: '/_showcase'
      fullPath: '/_showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/recover': {
      id: '/_auth/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/apps': {
      id: '/_app/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AppAdminAppsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/quotas': {
      id: '/_app/admin/quotas'
      path: '/quotas'
      fullPath: '/admin/quotas'
      preLoaderRoute: typeof AppAdminQuotasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId': {
      id: '/_app/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/': {
      id: '/_app/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof AppDocsIndexRouteImport
      parentRoute: typeof AppDocsRoute
    }
    '/_app/docs/$page': {
      id: '/_app/docs/$page'
      path: '/$page'
      fullPath: '/docs/$page'
      preLoaderRoute: typeof AppDocsPageRouteImport
      parentRoute: typeof AppDocsRoute
    }
    '/_app/docs/reference': {
      id: '/_app/docs/reference'
      path: '/reference'
      fullPath: '/docs/reference'
      preLoaderRoute: typeof AppDocsReferenceRouteImport
      parentRoute: typeof AppDocsRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/admin/reviews/$reviewId': {
      id: '/_app/admin/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/admin/reviews/$reviewId'
      preLoaderRoute: typeof AppAdminReviewsReviewIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/apps/$appId/': {
      id: '/_app/apps/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AppAppsAppIdIndexRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/environments': {
      id: '/_app/apps/$appId/environments'
      path: '/environments'
      fullPath: '/apps/$appId/environments'
      preLoaderRoute: typeof AppAppsAppIdEnvironmentsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/keys': {
      id: '/_app/apps/$appId/keys'
      path: '/keys'
      fullPath: '/apps/$appId/keys'
      preLoaderRoute: typeof AppAppsAppIdKeysRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/oauth': {
      id: '/_app/apps/$appId/oauth'
      path: '/oauth'
      fullPath: '/apps/$appId/oauth'
      preLoaderRoute: typeof AppAppsAppIdOauthRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/secrets': {
      id: '/_app/apps/$appId/secrets'
      path: '/secrets'
      fullPath: '/apps/$appId/secrets'
      preLoaderRoute: typeof AppAppsAppIdSecretsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/settings': {
      id: '/_app/apps/$appId/settings'
      path: '/settings'
      fullPath: '/apps/$appId/settings'
      preLoaderRoute: typeof AppAppsAppIdSettingsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/usage': {
      id: '/_app/apps/$appId/usage'
      path: '/usage'
      fullPath: '/apps/$appId/usage'
      preLoaderRoute: typeof AppAppsAppIdUsageRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAppsRoute: typeof AppAdminAppsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminQuotasRoute: typeof AppAdminQuotasRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminReviewsReviewIdRoute: typeof AppAdminReviewsReviewIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAppsRoute: AppAdminAppsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminQuotasRoute: AppAdminQuotasRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminReviewsReviewIdRoute: AppAdminReviewsReviewIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDocsRouteChildren {
  AppDocsPageRoute: typeof AppDocsPageRoute
  AppDocsReferenceRoute: typeof AppDocsReferenceRoute
  AppDocsIndexRoute: typeof AppDocsIndexRoute
}

const AppDocsRouteChildren: AppDocsRouteChildren = {
  AppDocsPageRoute: AppDocsPageRoute,
  AppDocsReferenceRoute: AppDocsReferenceRoute,
  AppDocsIndexRoute: AppDocsIndexRoute,
}

const AppDocsRouteWithChildren =
  AppDocsRoute._addFileChildren(AppDocsRouteChildren)

interface AppAppsAppIdRouteChildren {
  AppAppsAppIdEnvironmentsRoute: typeof AppAppsAppIdEnvironmentsRoute
  AppAppsAppIdKeysRoute: typeof AppAppsAppIdKeysRoute
  AppAppsAppIdOauthRoute: typeof AppAppsAppIdOauthRoute
  AppAppsAppIdSecretsRoute: typeof AppAppsAppIdSecretsRoute
  AppAppsAppIdSettingsRoute: typeof AppAppsAppIdSettingsRoute
  AppAppsAppIdUsageRoute: typeof AppAppsAppIdUsageRoute
  AppAppsAppIdIndexRoute: typeof AppAppsAppIdIndexRoute
}

const AppAppsAppIdRouteChildren: AppAppsAppIdRouteChildren = {
  AppAppsAppIdEnvironmentsRoute: AppAppsAppIdEnvironmentsRoute,
  AppAppsAppIdKeysRoute: AppAppsAppIdKeysRoute,
  AppAppsAppIdOauthRoute: AppAppsAppIdOauthRoute,
  AppAppsAppIdSecretsRoute: AppAppsAppIdSecretsRoute,
  AppAppsAppIdSettingsRoute: AppAppsAppIdSettingsRoute,
  AppAppsAppIdUsageRoute: AppAppsAppIdUsageRoute,
  AppAppsAppIdIndexRoute: AppAppsAppIdIndexRoute,
}

const AppAppsAppIdRouteWithChildren = AppAppsAppIdRoute._addFileChildren(
  AppAppsAppIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDocsRoute: typeof AppDocsRouteWithChildren
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppsAppIdRoute: typeof AppAppsAppIdRouteWithChildren
  AppAppsIndexRoute: typeof AppAppsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDocsRoute: AppDocsRouteWithChildren,
  AppOrganizationRoute: AppOrganizationRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppsAppIdRoute: AppAppsAppIdRouteWithChildren,
  AppAppsIndexRoute: AppAppsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecoverRoute: AuthRecoverRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
