// Enum values and constants from apps/activity-subgraph/src/helpers.ts on main.
// The warehouse must emit the same strings as the explorer subgraph so the
// webapp mapping and the parity check need no translation.

export const ACTION = {
  LOCK_CREATED: "LOCK_CREATED",
  LOCK_AMOUNT_INCREASED: "LOCK_AMOUNT_INCREASED",
  LOCK_EXTENDED: "LOCK_EXTENDED",
  LOCK_WITHDRAWN: "LOCK_WITHDRAWN",
  LOCK_PERMANENT: "LOCK_PERMANENT",
  LOCK_PERMANENT_UNLOCKED: "LOCK_PERMANENT_UNLOCKED",
  LOCK_TRANSFERRED: "LOCK_TRANSFERRED",
  LOCK_MERGED: "LOCK_MERGED",
  BOOST_VOTE: "BOOST_VOTE",
  BOOST_ABSTAIN: "BOOST_ABSTAIN",
  BOOST_POKE: "BOOST_POKE",
  PAIR_CREATED: "PAIR_CREATED",
  GAUGE_CREATED: "GAUGE_CREATED",
  GAUGE_KILLED: "GAUGE_KILLED",
  GAUGE_REVIVED: "GAUGE_REVIVED",
  BOOSTABLE_TOKEN_BURNED: "BOOSTABLE_TOKEN_BURNED",
  INCENTIVE_ADDED: "INCENTIVE_ADDED",
  REWARD_DISTRIBUTED: "REWARD_DISTRIBUTED",
  REWARD_NOTIFIED: "REWARD_NOTIFIED",
  THIRD_PARTY_GAUGE_CREATED: "THIRD_PARTY_GAUGE_CREATED",
  VALIDATOR_GAUGE_CREATED: "VALIDATOR_GAUGE_CREATED",
  VALIDATOR_LEFT: "VALIDATOR_LEFT",
  PERIOD_UPDATED: "PERIOD_UPDATED",
  EPOCH_PROCESSED: "EPOCH_PROCESSED",
  EMISSIONS_ENABLED: "EMISSIONS_ENABLED",
  REBASE_CLAIMED: "REBASE_CLAIMED",
  REBASE_CHECKPOINT: "REBASE_CHECKPOINT",
  MERKLE_CLAIMED: "MERKLE_CLAIMED",
  MERKLE_DISTRIBUTION_ADDED: "MERKLE_DISTRIBUTION_ADDED",
  SAVINGS_DEPOSIT: "SAVINGS_DEPOSIT",
  SAVINGS_WITHDRAW: "SAVINGS_WITHDRAW",
  SAVINGS_YIELD_CLAIMED: "SAVINGS_YIELD_CLAIMED",
  PROTOCOL_YIELD_RECEIVED: "PROTOCOL_YIELD_RECEIVED",
  STRATEGY_YIELD_RECEIVED: "STRATEGY_YIELD_RECEIVED",
  PCV_DISTRIBUTION: "PCV_DISTRIBUTION",
  PCV_DEBT_PAYMENT: "PCV_DEBT_PAYMENT",
  VOTE_FEE_CLAIMED: "VOTE_FEE_CLAIMED",
  VOTE_BRIBE_CLAIMED: "VOTE_BRIBE_CLAIMED",
  LP_ADDED: "LP_ADDED",
  LP_REMOVED: "LP_REMOVED",
  LP_STAKED: "LP_STAKED",
  LP_UNSTAKED: "LP_UNSTAKED",
  SWAP: "SWAP",
  POOL_CREATED: "POOL_CREATED",
} as const

export type ActionType = (typeof ACTION)[keyof typeof ACTION]

export const BOOST_CONTEXT = {
  MATCHBOX_GAUGE_BOOST: "MATCHBOX_GAUGE_BOOST",
  MEZO_VEBTC_PAIR_BOOST: "MEZO_VEBTC_PAIR_BOOST",
  UNKNOWN: "UNKNOWN",
} as const

export type BoostContext = (typeof BOOST_CONTEXT)[keyof typeof BOOST_CONTEXT]

export const SOURCE = {
  VOTING_ESCROW: "VOTING_ESCROW",
  BOOST_VOTER: "BOOST_VOTER",
  POOLS_VOTER: "POOLS_VOTER",
  THIRD_PARTY_VOTER: "THIRD_PARTY_VOTER",
  VALIDATORS_VOTER: "VALIDATORS_VOTER",
  CHAIN_FEE_SPLITTER: "CHAIN_FEE_SPLITTER",
  MEZO_CHAIN_SPLITTER: "MEZO_CHAIN_SPLITTER",
  MEZO_ECOSYSTEM_SPLITTER: "MEZO_ECOSYSTEM_SPLITTER",
  MEZO_MINTER: "MEZO_MINTER",
  MEZO_REBASE_DISTRIBUTOR: "MEZO_REBASE_DISTRIBUTOR",
  MEZO_MERKLE_DISTRIBUTOR: "MEZO_MERKLE_DISTRIBUTOR",
  MUSD_SAVINGS_RATE: "MUSD_SAVINGS_RATE",
  PCV: "PCV",
  POOL_FACTORY: "POOL_FACTORY",
  POOL: "POOL",
  GAUGE: "GAUGE",
  FEE_VOTING_REWARD: "FEE_VOTING_REWARD",
  BRIBE_VOTING_REWARD: "BRIBE_VOTING_REWARD",
} as const

export type ActivitySource = (typeof SOURCE)[keyof typeof SOURCE]

export const ZERO = 0n
export const ONE = 1n
export const WEEK = 604_800n
// 4 years in seconds, the ve-power saturation cap. Permanent locks are
// modelled as MAXTIME for the duration field.
export const MAXTIME = BigInt(4 * 365 * 86_400)

export const POKE_SELECTOR = "0x32145f90"
export const POKE_BOOST_SELECTOR = "0x673bbc86"
export const POKE_BOOSTS_SELECTOR = "0xd3672ab2"

// Order matters: resolveLockOwner returns the first escrow holding the
// tokenId, exactly as the subgraph does.
export const OWNER_LOOKUP_ESCROWS = [
  "0xb90fdad3dfd180458d62cc6acedc983d78e20122", // veMEZO mainnet
  "0xace816ca2bcc9b12c59799dcc5a959fb9b98111b", // veMEZO testnet
  "0x3d4b1b884a7a1e59fe8589a3296ec8f8cbb6f279", // veBTC mainnet
  "0x38e35d92e6bfc6787272a62345856b13ea12130a", // veBTC testnet
] as const

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"
